### ISSUE TITLE
How to Use

### ISSUE THREAD

**Issue by btootoonchi** [lsinfo3/yomo-browser-plugin#3]
Hi, 

I would like to use YoMo plug-in in my Firefox browser.  I am going to test YouTube streaming for my research. Please help me to add it into my browser. 

I am sorry. I do not know how I can contact you, so I have created an issue. 

Best regards,
Babak

**Comment by anika-seufert** [comment]
The YoMo-Plugin is a add-on for Firefox. If you want to use it you can download the file [https://github.com/lsinfo3/yomo-browser-plugin/blob/master/yomo-42.florian.wamser%40informatik.uni-wuerzburg.de.xpi](url) and add it to your Firefox browser. But be aware of the fact that the plugin is not verified yet! That means that it only works for the _Firefox Developer Edition_ or an _old version of Firefox (40 or older)_.
